#pragma once

#include <string>
#include <vector>
#include <random>
#include <algorithm>

namespace is::games::country_elimination {

struct QuizQuestion {
    std::string question;
    std::string options[4]; // A, B, C, D
    int correctIndex;       // 0–3
};

// ── Comprehensive Geography & Country Quiz Catalog ───────────────────────────

inline const std::vector<QuizQuestion>& getQuizCatalog() {
    static const std::vector<QuizQuestion> catalog = {
        // ── Capitals ─────────────────────────────────────────────────────
        {"What is the capital of France?",
         {"Berlin", "Madrid", "Paris", "Rome"}, 2},
        {"What is the capital of Japan?",
         {"Seoul", "Tokyo", "Beijing", "Osaka"}, 1},
        {"What is the capital of Australia?",
         {"Sydney", "Melbourne", "Canberra", "Brisbane"}, 2},
        {"What is the capital of Canada?",
         {"Toronto", "Vancouver", "Montreal", "Ottawa"}, 3},
        {"What is the capital of Brazil?",
         {"Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador"}, 2},
        {"What is the capital of Egypt?",
         {"Alexandria", "Cairo", "Luxor", "Giza"}, 1},
        {"What is the capital of Turkey?",
         {"Istanbul", "Ankara", "Izmir", "Antalya"}, 1},
        {"What is the capital of South Africa?",
         {"Johannesburg", "Cape Town", "Pretoria", "Durban"}, 2},
        {"What is the capital of India?",
         {"Mumbai", "New Delhi", "Kolkata", "Bangalore"}, 1},
        {"What is the capital of Germany?",
         {"Munich", "Hamburg", "Berlin", "Frankfurt"}, 2},
        {"What is the capital of Italy?",
         {"Milan", "Venice", "Rome", "Naples"}, 2},
        {"What is the capital of Spain?",
         {"Barcelona", "Seville", "Madrid", "Valencia"}, 2},
        {"What is the capital of China?",
         {"Shanghai", "Beijing", "Hong Kong", "Guangzhou"}, 1},
        {"What is the capital of Russia?",
         {"St. Petersburg", "Moscow", "Novosibirsk", "Kazan"}, 1},
        {"What is the capital of Mexico?",
         {"Guadalajara", "Cancun", "Monterrey", "Mexico City"}, 3},
        {"What is the capital of Argentina?",
         {"Cordoba", "Buenos Aires", "Mendoza", "Rosario"}, 1},
        {"What is the capital of Thailand?",
         {"Chiang Mai", "Phuket", "Pattaya", "Bangkok"}, 3},
        {"What is the capital of South Korea?",
         {"Busan", "Incheon", "Seoul", "Daegu"}, 2},
        {"What is the capital of Poland?",
         {"Krakow", "Warsaw", "Gdansk", "Wroclaw"}, 1},
        {"What is the capital of Sweden?",
         {"Gothenburg", "Malmo", "Stockholm", "Uppsala"}, 2},
        {"What is the capital of Norway?",
         {"Bergen", "Oslo", "Stavanger", "Tromso"}, 1},
        {"What is the capital of Finland?",
         {"Turku", "Tampere", "Helsinki", "Espoo"}, 2},
        {"What is the capital of Greece?",
         {"Thessaloniki", "Athens", "Crete", "Patras"}, 1},
        {"What is the capital of Portugal?",
         {"Porto", "Lisbon", "Faro", "Braga"}, 1},
        {"What is the capital of New Zealand?",
         {"Auckland", "Christchurch", "Wellington", "Hamilton"}, 2},
        {"What is the capital of Peru?",
         {"Cusco", "Lima", "Arequipa", "Trujillo"}, 1},
        {"What is the capital of Colombia?",
         {"Medellin", "Cali", "Bogota", "Cartagena"}, 2},
        {"What is the capital of Kenya?",
         {"Mombasa", "Nairobi", "Kisumu", "Nakuru"}, 1},
        {"What is the capital of Nigeria?",
         {"Lagos", "Kano", "Abuja", "Ibadan"}, 2},
        {"What is the capital of Vietnam?",
         {"Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"}, 1},
        {"What is the capital of Switzerland?",
         {"Zurich", "Geneva", "Bern", "Basel"}, 2},
        {"What is the capital of Austria?",
         {"Salzburg", "Graz", "Vienna", "Innsbruck"}, 2},
        {"What is the capital of Ireland?",
         {"Cork", "Dublin", "Galway", "Limerick"}, 1},
        {"What is the capital of Czech Republic?",
         {"Brno", "Prague", "Ostrava", "Pilsen"}, 1},
        {"What is the capital of Hungary?",
         {"Debrecen", "Szeged", "Budapest", "Pecs"}, 2},

        // ── Continents & Geography ───────────────────────────────────────
        {"Which continent has the most countries?",
         {"Asia", "Europe", "Africa", "South America"}, 2},
        {"What is the largest continent by area?",
         {"Africa", "North America", "Asia", "Europe"}, 2},
        {"What is the smallest continent?",
         {"Europe", "Antarctica", "Australia", "South America"}, 2},
        {"Which ocean is the largest?",
         {"Atlantic", "Indian", "Pacific", "Arctic"}, 2},
        {"What is the longest river in the world?",
         {"Amazon", "Nile", "Mississippi", "Yangtze"}, 1},
        {"What is the largest desert in the world?",
         {"Sahara", "Antarctic", "Arabian", "Gobi"}, 1},
        {"What is the highest mountain in the world?",
         {"K2", "Kangchenjunga", "Mount Everest", "Lhotse"}, 2},
        {"Which country has the most islands?",
         {"Indonesia", "Philippines", "Sweden", "Japan"}, 2},
        {"What is the deepest ocean trench?",
         {"Tonga Trench", "Mariana Trench", "Java Trench", "Puerto Rico Trench"}, 1},
        {"Which lake is the largest by area?",
         {"Lake Victoria", "Lake Superior", "Caspian Sea", "Lake Baikal"}, 2},
        {"What is the driest place on Earth?",
         {"Sahara Desert", "Atacama Desert", "Death Valley", "Arabian Desert"}, 1},
        {"What sea lies between Europe and Africa?",
         {"Red Sea", "Black Sea", "Mediterranean Sea", "Caspian Sea"}, 2},

        // ── Flags & Symbols ──────────────────────────────────────────────
        {"Which country's flag has a maple leaf?",
         {"USA", "Canada", "Ireland", "Japan"}, 1},
        {"Which flag has a Union Jack in the corner?",
         {"New Zealand", "France", "Ireland", "Germany"}, 0},
        {"Which country has a red circle on a white background?",
         {"China", "South Korea", "Japan", "Bangladesh"}, 2},
        {"Which flag has green, white, and orange stripes?",
         {"Italy", "Ireland", "India", "Ivory Coast"}, 1},
        {"Which country has a crescent moon on its flag?",
         {"India", "Turkey", "Morocco", "Iran"}, 1},
        {"Which flag features an eagle on a cactus?",
         {"Mexico", "Albania", "Egypt", "Germany"}, 0},
        {"Which country has a dragon on its flag?",
         {"China", "Japan", "Wales", "Thailand"}, 2},
        {"Which flag is the only non-rectangular national flag?",
         {"Switzerland", "Nepal", "Vatican City", "Bhutan"}, 1},
        {"Which country's flag has six horizontal stripes: blue and white?",
         {"Israel", "Greece", "Argentina", "Finland"}, 1},

        // ── Countries & Facts ────────────────────────────────────────────
        {"What is the largest country by area?",
         {"Canada", "China", "USA", "Russia"}, 3},
        {"What is the smallest country in the world?",
         {"Monaco", "Vatican City", "San Marino", "Liechtenstein"}, 1},
        {"Which country has the largest population?",
         {"India", "USA", "China", "Indonesia"}, 0},
        {"Which country spans the most time zones?",
         {"Russia", "USA", "China", "France"}, 3},
        {"Which is the only country on all 4 hemispheres?",
         {"Brazil", "Kiribati", "Indonesia", "Ecuador"}, 1},
        {"In which country is Machu Picchu?",
         {"Mexico", "Colombia", "Bolivia", "Peru"}, 3},
        {"Where are the Pyramids of Giza?",
         {"Sudan", "Libya", "Egypt", "Morocco"}, 2},
        {"In which country is the Taj Mahal?",
         {"Pakistan", "Bangladesh", "Nepal", "India"}, 3},
        {"The Great Wall is in which country?",
         {"Japan", "China", "Mongolia", "Korea"}, 1},
        {"In which country is Mount Kilimanjaro?",
         {"Kenya", "Ethiopia", "Tanzania", "Uganda"}, 2},
        {"What country is known as the Land of the Rising Sun?",
         {"China", "Thailand", "Japan", "South Korea"}, 2},
        {"Which country is shaped like a boot?",
         {"Greece", "Portugal", "Spain", "Italy"}, 3},
        {"Which two countries share the longest border?",
         {"USA & Mexico", "Russia & China", "USA & Canada", "Brazil & Argentina"}, 2},
        {"Which country has the most UNESCO World Heritage Sites?",
         {"China", "France", "Italy", "Spain"}, 2},
        {"What is the most visited country in the world?",
         {"USA", "Spain", "France", "Italy"}, 2},
        {"Which African country was never colonized?",
         {"Nigeria", "Ethiopia", "South Africa", "Kenya"}, 1},
        {"Which country produces the most coffee?",
         {"Colombia", "Vietnam", "Ethiopia", "Brazil"}, 3},
        {"What country is famous for fjords?",
         {"Sweden", "Iceland", "Norway", "Finland"}, 2},
        {"Which country has the most volcanoes?",
         {"Japan", "Indonesia", "Iceland", "Philippines"}, 1},
        {"Panama Canal connects which two oceans?",
         {"Atlantic & Indian", "Pacific & Indian", "Atlantic & Pacific", "Atlantic & Arctic"}, 2},
        {"Which country is home to the Amazon Rainforest?",
         {"Peru", "Colombia", "Brazil", "Venezuela"}, 2},
        {"What is the official language of Brazil?",
         {"Spanish", "Portuguese", "English", "French"}, 1},
        {"Which Mediterranean island belongs to France?",
         {"Sardinia", "Corsica", "Crete", "Sicily"}, 1},
        {"What country has the most natural lakes?",
         {"Sweden", "USA", "Canada", "Finland"}, 2},
        {"Which country is known as the Land Down Under?",
         {"New Zealand", "South Africa", "Australia", "Argentina"}, 2},

        // ── Currencies ───────────────────────────────────────────────────
        {"What currency is used in Japan?",
         {"Won", "Yuan", "Yen", "Baht"}, 2},
        {"What currency is used in the UK?",
         {"Euro", "Dollar", "Pound Sterling", "Franc"}, 2},
        {"What is the currency of India?",
         {"Rupee", "Ringgit", "Ruble", "Real"}, 0},
        {"What currency do most EU countries use?",
         {"Dollar", "Franc", "Pound", "Euro"}, 3},
        {"What is the currency of South Korea?",
         {"Yen", "Won", "Yuan", "Dong"}, 1},
        {"What currency is used in Mexico?",
         {"Dollar", "Peso", "Real", "Sol"}, 1},
        {"What is the currency of Switzerland?",
         {"Euro", "Krona", "Swiss Franc", "Mark"}, 2},

        // ── Languages ────────────────────────────────────────────────────
        {"What is the most spoken language in the world?",
         {"Spanish", "English", "Mandarin Chinese", "Hindi"}, 2},
        {"Which language is the most spoken in South America?",
         {"Portuguese", "Spanish", "English", "French"}, 1},
        {"In which country is Swahili spoken?",
         {"Nigeria", "South Africa", "Kenya", "Egypt"}, 2},
        {"What language is primarily spoken in Austria?",
         {"French", "German", "Dutch", "Italian"}, 1},
        {"How many official languages does Switzerland have?",
         {"2", "3", "4", "5"}, 2},

        // ── Miscellaneous Geo Trivia ─────────────────────────────────────
        {"What is the northernmost capital city in the world?",
         {"Helsinki", "Reykjavik", "Oslo", "Tallinn"}, 1},
        {"Which country has the longest coastline?",
         {"Australia", "Indonesia", "Canada", "Russia"}, 2},
        {"What strait separates Europe from Asia?",
         {"Strait of Gibraltar", "Bosphorus", "Strait of Malacca", "Strait of Hormuz"}, 1},
        {"Which country is both in Europe and Asia?",
         {"Russia", "Turkey", "Egypt", "Georgia"}, 1},
        {"What is Earth's largest island (not continent)?",
         {"Madagascar", "Borneo", "Greenland", "New Guinea"}, 2},
        {"How many countries are in the United Kingdom?",
         {"2", "3", "4", "5"}, 2},
        {"Which river flows through London?",
         {"Seine", "Rhine", "Danube", "Thames"}, 3},
        {"What is the capital of Iceland?",
         {"Bergen", "Reykjavik", "Helsinki", "Nuuk"}, 1},
        {"Which U.S. state was the last to join?",
         {"Alaska", "Hawaii", "Texas", "California"}, 1},
        {"What is the highest waterfall in the world?",
         {"Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"}, 1},
        {"In which country is the Sahara Desert?",
         {"Saudi Arabia", "Egypt", "Libya", "All of these"}, 3},
        {"Which country borders the most other countries?",
         {"Russia", "China", "Brazil", "Germany"}, 1},
        {"What is the Ring of Fire?",
         {"A volcanic zone", "A desert", "A river", "A mountain range"}, 0},
        {"On which continent is the South Pole?",
         {"Arctic", "Antarctica", "Australia", "South America"}, 1},
        {"Which European city has canals instead of streets?",
         {"Amsterdam", "Venice", "Bruges", "Stockholm"}, 1},
        {"What is the only continent without a desert?",
         {"Europe", "Antarctica", "South America", "Asia"}, 0},
        {"Which country is known for the Great Barrier Reef?",
         {"Indonesia", "Philippines", "Australia", "Fiji"}, 2},
        {"What mountain range separates Europe from Asia?",
         {"Alps", "Himalayas", "Andes", "Ural Mountains"}, 3},
        {"What is the world's most populous city?",
         {"Shanghai", "Tokyo", "Delhi", "Sao Paulo"}, 1},
        {"Which is the coldest inhabited place on Earth?",
         {"Antarctica", "Oymyakon, Russia", "Nuuk, Greenland", "Barrow, Alaska"}, 1},
    };
    return catalog;
}

/// Return a shuffled sequence of question indices for variety.
inline std::vector<int> shuffledQuizIndices(std::mt19937& rng) {
    auto& catalog = getQuizCatalog();
    std::vector<int> idx(catalog.size());
    for (size_t i = 0; i < idx.size(); ++i) idx[i] = static_cast<int>(i);
    std::shuffle(idx.begin(), idx.end(), rng);
    return idx;
}

} // namespace is::games::country_elimination
