#pragma once

#include <string>
#include <vector>
#include <random>
#include <algorithm>

namespace is::games::country_elimination {

struct QuizQuestion {
    std::string question;
    std::string options[4]; // A, B, C, D
    int correctIndex;       // 0–3
};

// ── Comprehensive Geography & Country Quiz Catalog ───────────────────────────

inline const std::vector<QuizQuestion>& getQuizCatalog() {
    static const std::vector<QuizQuestion> catalog = {
        // ── Capitals ─────────────────────────────────────────────────────
        {"What is the capital of France?",
         {"Berlin", "Madrid", "Paris", "Rome"}, 2},
        {"What is the capital of Japan?",
         {"Seoul", "Tokyo", "Beijing", "Osaka"}, 1},
        {"What is the capital of Australia?",
         {"Sydney", "Melbourne", "Canberra", "Brisbane"}, 2},
        {"What is the capital of Canada?",
         {"Toronto", "Vancouver", "Montreal", "Ottawa"}, 3},
        {"What is the capital of Brazil?",
         {"Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador"}, 2},
        {"What is the capital of Egypt?",
         {"Alexandria", "Cairo", "Luxor", "Giza"}, 1},
        {"What is the capital of Turkey?",
         {"Istanbul", "Ankara", "Izmir", "Antalya"}, 1},
        {"What is the capital of South Africa?",
         {"Johannesburg", "Cape Town", "Pretoria", "Durban"}, 2},
        {"What is the capital of India?",
         {"Mumbai", "New Delhi", "Kolkata", "Bangalore"}, 1},
        {"What is the capital of Germany?",
         {"Munich", "Hamburg", "Berlin", "Frankfurt"}, 2},
        {"What is the capital of Italy?",
         {"Milan", "Venice", "Rome", "Naples"}, 2},
        {"What is the capital of Spain?",
         {"Barcelona", "Seville", "Madrid", "Valencia"}, 2},
        {"What is the capital of China?",
         {"Shanghai", "Beijing", "Hong Kong", "Guangzhou"}, 1},
        {"What is the capital of Russia?",
         {"St. Petersburg", "Moscow", "Novosibirsk", "Kazan"}, 1},
        {"What is the capital of Mexico?",
         {"Guadalajara", "Cancun", "Monterrey", "Mexico City"}, 3},
        {"What is the capital of Argentina?",
         {"Cordoba", "Buenos Aires", "Mendoza", "Rosario"}, 1},
        {"What is the capital of Thailand?",
         {"Chiang Mai", "Phuket", "Pattaya", "Bangkok"}, 3},
        {"What is the capital of South Korea?",
         {"Busan", "Incheon", "Seoul", "Daegu"}, 2},
        {"What is the capital of Poland?",
         {"Krakow", "Warsaw", "Gdansk", "Wroclaw"}, 1},
        {"What is the capital of Sweden?",
         {"Gothenburg", "Malmo", "Stockholm", "Uppsala"}, 2},
        {"What is the capital of Norway?",
         {"Bergen", "Oslo", "Stavanger", "Tromso"}, 1},
        {"What is the capital of Finland?",
         {"Turku", "Tampere", "Helsinki", "Espoo"}, 2},
        {"What is the capital of Greece?",
         {"Thessaloniki", "Athens", "Crete", "Patras"}, 1},
        {"What is the capital of Portugal?",
         {"Porto", "Lisbon", "Faro", "Braga"}, 1},
        {"What is the capital of New Zealand?",
         {"Auckland", "Christchurch", "Wellington", "Hamilton"}, 2},
        {"What is the capital of Peru?",
         {"Cusco", "Lima", "Arequipa", "Trujillo"}, 1},
        {"What is the capital of Colombia?",
         {"Medellin", "Cali", "Bogota", "Cartagena"}, 2},
        {"What is the capital of Kenya?",
         {"Mombasa", "Nairobi", "Kisumu", "Nakuru"}, 1},
        {"What is the capital of Nigeria?",
         {"Lagos", "Kano", "Abuja", "Ibadan"}, 2},
        {"What is the capital of Vietnam?",
         {"Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"}, 1},
        {"What is the capital of Switzerland?",
         {"Zurich", "Geneva", "Bern", "Basel"}, 2},
        {"What is the capital of Austria?",
         {"Salzburg", "Graz", "Vienna", "Innsbruck"}, 2},
        {"What is the capital of Ireland?",
         {"Cork", "Dublin", "Galway", "Limerick"}, 1},
        {"What is the capital of Czech Republic?",
         {"Brno", "Prague", "Ostrava", "Pilsen"}, 1},
        {"What is the capital of Hungary?",
         {"Debrecen", "Szeged", "Budapest", "Pecs"}, 2},

        // ── Continents & Geography ───────────────────────────────────────
        {"Which continent has the most countries?",
         {"Asia", "Europe", "Africa", "South America"}, 2},
        {"What is the largest continent by area?",
         {"Africa", "North America", "Asia", "Europe"}, 2},
        {"What is the smallest continent?",
         {"Europe", "Antarctica", "Australia", "South America"}, 2},
        {"Which ocean is the largest?",
         {"Atlantic", "Indian", "Pacific", "Arctic"}, 2},
        {"What is the longest river in the world?",
         {"Amazon", "Nile", "Mississippi", "Yangtze"}, 1},
        {"What is the largest desert in the world?",
         {"Sahara", "Antarctic", "Arabian", "Gobi"}, 1},
        {"What is the highest mountain in the world?",
         {"K2", "Kangchenjunga", "Mount Everest", "Lhotse"}, 2},
        {"Which country has the most islands?",
         {"Indonesia", "Philippines", "Sweden", "Japan"}, 2},
        {"What is the deepest ocean trench?",
         {"Tonga Trench", "Mariana Trench", "Java Trench", "Puerto Rico Trench"}, 1},
        {"Which lake is the largest by area?",
         {"Lake Victoria", "Lake Superior", "Caspian Sea", "Lake Baikal"}, 2},
        {"What is the driest place on Earth?",
         {"Sahara Desert", "Atacama Desert", "Death Valley", "Arabian Desert"}, 1},
        {"What sea lies between Europe and Africa?",
         {"Red Sea", "Black Sea", "Mediterranean Sea", "Caspian Sea"}, 2},

        // ── Flags & Symbols ──────────────────────────────────────────────
        {"Which country's flag has a maple leaf?",
         {"USA", "Canada", "Ireland", "Japan"}, 1},
        {"Which flag has a Union Jack in the corner?",
         {"New Zealand", "France", "Ireland", "Germany"}, 0},
        {"Which country has a red circle on a white background?",
         {"China", "South Korea", "Japan", "Bangladesh"}, 2},
        {"Which flag has green, white, and orange stripes?",
         {"Italy", "Ireland", "India", "Ivory Coast"}, 1},
        {"Which country has a crescent moon on its flag?",
         {"India", "Turkey", "Morocco", "Iran"}, 1},
        {"Which flag features an eagle on a cactus?",
         {"Mexico", "Albania", "Egypt", "Germany"}, 0},
        {"Which country has a dragon on its flag?",
         {"China", "Japan", "Wales", "Thailand"}, 2},
        {"Which flag is the only non-rectangular national flag?",
         {"Switzerland", "Nepal", "Vatican City", "Bhutan"}, 1},
        {"Which country's flag has six horizontal stripes: blue and white?",
         {"Israel", "Greece", "Argentina", "Finland"}, 1},

        // ── Countries & Facts ────────────────────────────────────────────
        {"What is the largest country by area?",
         {"Canada", "China", "USA", "Russia"}, 3},
        {"What is the smallest country in the world?",
         {"Monaco", "Vatican City", "San Marino", "Liechtenstein"}, 1},
        {"Which country has the largest population?",
         {"India", "USA", "China", "Indonesia"}, 0},
        {"Which country spans the most time zones?",
         {"Russia", "USA", "China", "France"}, 3},
        {"Which is the only country on all 4 hemispheres?",
         {"Brazil", "Kiribati", "Indonesia", "Ecuador"}, 1},
        {"In which country is Machu Picchu?",
         {"Mexico", "Colombia", "Bolivia", "Peru"}, 3},
        {"Where are the Pyramids of Giza?",
         {"Sudan", "Libya", "Egypt", "Morocco"}, 2},
        {"In which country is the Taj Mahal?",
         {"Pakistan", "Bangladesh", "Nepal", "India"}, 3},
        {"The Great Wall is in which country?",
         {"Japan", "China", "Mongolia", "Korea"}, 1},
        {"In which country is Mount Kilimanjaro?",
         {"Kenya", "Ethiopia", "Tanzania", "Uganda"}, 2},
        {"What country is known as the Land of the Rising Sun?",
         {"China", "Thailand", "Japan", "South Korea"}, 2},
        {"Which country is shaped like a boot?",
         {"Greece", "Portugal", "Spain", "Italy"}, 3},
        {"Which two countries share the longest border?",
         {"USA & Mexico", "Russia & China", "USA & Canada", "Brazil & Argentina"}, 2},
        {"Which country has the most UNESCO World Heritage Sites?",
         {"China", "France", "Italy", "Spain"}, 2},
        {"What is the most visited country in the world?",
         {"USA", "Spain", "France", "Italy"}, 2},
        {"Which African country was never colonized?",
         {"Nigeria", "Ethiopia", "South Africa", "Kenya"}, 1},
        {"Which country produces the most coffee?",
         {"Colombia", "Vietnam", "Ethiopia", "Brazil"}, 3},
        {"What country is famous for fjords?",
         {"Sweden", "Iceland", "Norway", "Finland"}, 2},
        {"Which country has the most volcanoes?",
         {"Japan", "Indonesia", "Iceland", "Philippines"}, 1},
        {"Panama Canal connects which two oceans?",
         {"Atlantic & Indian", "Pacific & Indian", "Atlantic & Pacific", "Atlantic & Arctic"}, 2},
        {"Which country is home to the Amazon Rainforest?",
         {"Peru", "Colombia", "Brazil", "Venezuela"}, 2},
        {"What is the official language of Brazil?",
         {"Spanish", "Portuguese", "English", "French"}, 1},
        {"Which Mediterranean island belongs to France?",
         {"Sardinia", "Corsica", "Crete", "Sicily"}, 1},
        {"What country has the most natural lakes?",
         {"Sweden", "USA", "Canada", "Finland"}, 2},
        {"Which country is known as the Land Down Under?",
         {"New Zealand", "South Africa", "Australia", "Argentina"}, 2},

        // ── Currencies ───────────────────────────────────────────────────
        {"What currency is used in Japan?",
         {"Won", "Yuan", "Yen", "Baht"}, 2},
        {"What currency is used in the UK?",
         {"Euro", "Dollar", "Pound Sterling", "Franc"}, 2},
        {"What is the currency of India?",
         {"Rupee", "Ringgit", "Ruble", "Real"}, 0},
        {"What currency do most EU countries use?",
         {"Dollar", "Franc", "Pound", "Euro"}, 3},
        {"What is the currency of South Korea?",
         {"Yen", "Won", "Yuan", "Dong"}, 1},
        {"What currency is used in Mexico?",
         {"Dollar", "Peso", "Real", "Sol"}, 1},
        {"What is the currency of Switzerland?",
         {"Euro", "Krona", "Swiss Franc", "Mark"}, 2},

        // ── Languages ────────────────────────────────────────────────────
        {"What is the most spoken language in the world?",
         {"Spanish", "English", "Mandarin Chinese", "Hindi"}, 2},
        {"Which language is the most spoken in South America?",
         {"Portuguese", "Spanish", "English", "French"}, 1},
        {"In which country is Swahili spoken?",
         {"Nigeria", "South Africa", "Kenya", "Egypt"}, 2},
        {"What language is primarily spoken in Austria?",
         {"French", "German", "Dutch", "Italian"}, 1},
        {"How many official languages does Switzerland have?",
         {"2", "3", "4", "5"}, 2},

        // ── Miscellaneous Geo Trivia ─────────────────────────────────────
        {"What is the northernmost capital city in the world?",
         {"Helsinki", "Reykjavik", "Oslo", "Tallinn"}, 1},
        {"Which country has the longest coastline?",
         {"Australia", "Indonesia", "Canada", "Russia"}, 2},
        {"What strait separates Europe from Asia?",
         {"Strait of Gibraltar", "Bosphorus", "Strait of Malacca", "Strait of Hormuz"}, 1},
        {"Which country is both in Europe and Asia?",
         {"Russia", "Turkey", "Egypt", "Georgia"}, 1},
        {"What is Earth's largest island (not continent)?",
         {"Madagascar", "Borneo", "Greenland", "New Guinea"}, 2},
        {"How many countries are in the United Kingdom?",
         {"2", "3", "4", "5"}, 2},
        {"Which river flows through London?",
         {"Seine", "Rhine", "Danube", "Thames"}, 3},
        {"What is the capital of Iceland?",
         {"Bergen", "Reykjavik", "Helsinki", "Nuuk"}, 1},
        {"Which U.S. state was the last to join?",
         {"Alaska", "Hawaii", "Texas", "California"}, 1},
        {"What is the highest waterfall in the world?",
         {"Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"}, 1},
        {"In which country is the Sahara Desert?",
         {"Saudi Arabia", "Egypt", "Libya", "All of these"}, 3},
        {"Which country borders the most other countries?",
         {"Russia", "China", "Brazil", "Germany"}, 1},
        {"What is the Ring of Fire?",
         {"A volcanic zone", "A desert", "A river", "A mountain range"}, 0},
        {"On which continent is the South Pole?",
         {"Arctic", "Antarctica", "Australia", "South America"}, 1},
        {"Which European city has canals instead of streets?",
         {"Amsterdam", "Venice", "Bruges", "Stockholm"}, 1},
        {"What is the only continent without a desert?",
         {"Europe", "Antarctica", "South America", "Asia"}, 0},
        {"Which country is known for the Great Barrier Reef?",
         {"Indonesia", "Philippines", "Australia", "Fiji"}, 2},
        {"What mountain range separates Europe from Asia?",
         {"Alps", "Himalayas", "Andes", "Ural Mountains"}, 3},
        {"What is the world's most populous city?",
         {"Shanghai", "Tokyo", "Delhi", "Sao Paulo"}, 1},
        {"Which is the coldest inhabited place on Earth?",
         {"Antarctica", "Oymyakon, Russia", "Nuuk, Greenland", "Barrow, Alaska"}, 1},

        // ── More Capitals ────────────────────────────────────────────────
        {"What is the capital of Morocco?",
         {"Casablanca", "Marrakech", "Rabat", "Fez"}, 2},
        {"What is the capital of Chile?",
         {"Valparaiso", "Santiago", "Concepcion", "Antofagasta"}, 1},
        {"What is the capital of Cuba?",
         {"Santiago de Cuba", "Havana", "Trinidad", "Camaguey"}, 1},
        {"What is the capital of Pakistan?",
         {"Karachi", "Lahore", "Islamabad", "Rawalpindi"}, 2},
        {"What is the capital of Sri Lanka?",
         {"Colombo", "Kandy", "Sri Jayawardenepura Kotte", "Galle"}, 2},
        {"What is the capital of Myanmar?",
         {"Yangon", "Mandalay", "Naypyidaw", "Bagan"}, 2},
        {"What is the capital of Mongolia?",
         {"Darkhan", "Erdenet", "Ulaanbaatar", "Choibalsan"}, 2},
        {"What is the capital of Kazakhstan?",
         {"Almaty", "Astana", "Shymkent", "Karaganda"}, 1},
        {"What is the capital of Tanzania?",
         {"Dar es Salaam", "Dodoma", "Arusha", "Mwanza"}, 1},
        {"What is the capital of Ethiopia?",
         {"Dire Dawa", "Addis Ababa", "Gondar", "Bahir Dar"}, 1},
        {"What is the capital of Ukraine?",
         {"Odessa", "Lviv", "Kyiv", "Kharkiv"}, 2},
        {"What is the capital of Romania?",
         {"Cluj-Napoca", "Timisoara", "Bucharest", "Iasi"}, 2},
        {"What is the capital of Croatia?",
         {"Split", "Dubrovnik", "Zagreb", "Rijeka"}, 2},
        {"What is the capital of Serbia?",
         {"Novi Sad", "Belgrade", "Nis", "Kragujevac"}, 1},
        {"What is the capital of Malaysia?",
         {"Penang", "Kuala Lumpur", "Johor Bahru", "Malacca"}, 1},
        {"What is the capital of Philippines?",
         {"Cebu", "Davao", "Manila", "Quezon City"}, 2},
        {"What is the capital of Indonesia?",
         {"Surabaya", "Bandung", "Jakarta", "Bali"}, 2},
        {"What is the capital of Bangladesh?",
         {"Chittagong", "Dhaka", "Sylhet", "Khulna"}, 1},
        {"What is the capital of Iran?",
         {"Isfahan", "Shiraz", "Tehran", "Tabriz"}, 2},
        {"What is the capital of Iraq?",
         {"Basra", "Mosul", "Baghdad", "Erbil"}, 2},
        {"What is the capital of Saudi Arabia?",
         {"Jeddah", "Mecca", "Riyadh", "Medina"}, 2},
        {"What is the capital of Israel?",
         {"Tel Aviv", "Jerusalem", "Haifa", "Eilat"}, 1},
        {"What is the capital of Jordan?",
         {"Aqaba", "Irbid", "Amman", "Zarqa"}, 2},
        {"What is the capital of Lebanon?",
         {"Tripoli", "Beirut", "Sidon", "Byblos"}, 1},
        {"What is the capital of Venezuela?",
         {"Maracaibo", "Valencia", "Caracas", "Barquisimeto"}, 2},
        {"What is the capital of Ecuador?",
         {"Guayaquil", "Cuenca", "Quito", "Manta"}, 2},
        {"What is the capital of Bolivia?",
         {"La Paz", "Sucre", "Santa Cruz", "Cochabamba"}, 1},
        {"What is the capital of Paraguay?",
         {"Ciudad del Este", "Asuncion", "Encarnacion", "Concepcion"}, 1},
        {"What is the capital of Uruguay?",
         {"Salto", "Punta del Este", "Montevideo", "Colonia"}, 2},
        {"What is the capital of Jamaica?",
         {"Montego Bay", "Kingston", "Spanish Town", "Ocho Rios"}, 1},
        {"What is the capital of Panama?",
         {"Colon", "David", "Panama City", "Santiago"}, 2},
        {"What is the capital of Costa Rica?",
         {"Limon", "San Jose", "Heredia", "Cartago"}, 1},
        {"What is the capital of Guatemala?",
         {"Antigua", "Quetzaltenango", "Guatemala City", "Flores"}, 2},
        {"What is the capital of Denmark?",
         {"Aarhus", "Odense", "Copenhagen", "Aalborg"}, 2},
        {"What is the capital of Belgium?",
         {"Antwerp", "Ghent", "Brussels", "Bruges"}, 2},
        {"What is the capital of Netherlands?",
         {"Rotterdam", "Amsterdam", "The Hague", "Utrecht"}, 1},
        {"What is the capital of Lithuania?",
         {"Kaunas", "Vilnius", "Klaipeda", "Siauliai"}, 1},
        {"What is the capital of Latvia?",
         {"Liepaja", "Daugavpils", "Riga", "Jurmala"}, 2},
        {"What is the capital of Estonia?",
         {"Tartu", "Parnu", "Tallinn", "Narva"}, 2},
        {"What is the capital of Slovenia?",
         {"Maribor", "Ljubljana", "Celje", "Koper"}, 1},
        {"What is the capital of Slovakia?",
         {"Kosice", "Bratislava", "Zilina", "Presov"}, 1},
        {"What is the capital of Albania?",
         {"Durres", "Vlore", "Tirana", "Shkoder"}, 2},
        {"What is the capital of Georgia?",
         {"Batumi", "Kutaisi", "Tbilisi", "Rustavi"}, 2},
        {"What is the capital of Nepal?",
         {"Pokhara", "Kathmandu", "Biratnagar", "Lalitpur"}, 1},

        // ── Rivers & Bodies of Water ─────────────────────────────────────
        {"Which river flows through Paris?",
         {"Rhine", "Danube", "Seine", "Loire"}, 2},
        {"The Danube flows into which sea?",
         {"Mediterranean", "Black Sea", "Caspian Sea", "Adriatic Sea"}, 1},
        {"Which river is the longest in Africa?",
         {"Congo", "Niger", "Nile", "Zambezi"}, 2},
        {"The Ganges River is sacred in which religion?",
         {"Buddhism", "Islam", "Hinduism", "Sikhism"}, 2},
        {"Which is the deepest lake in the world?",
         {"Lake Superior", "Lake Baikal", "Lake Tanganyika", "Lake Malawi"}, 1},
        {"What is the largest freshwater lake by surface area?",
         {"Lake Victoria", "Lake Superior", "Lake Huron", "Lake Michigan"}, 1},
        {"The Amazon River is mainly in which country?",
         {"Peru", "Colombia", "Brazil", "Bolivia"}, 2},
        {"Which strait connects the Atlantic and Pacific?",
         {"Strait of Malacca", "Bering Strait", "Strait of Magellan", "Strait of Gibraltar"}, 2},
        {"Which sea is the saltiest in the world?",
         {"Red Sea", "Dead Sea", "Mediterranean Sea", "Caspian Sea"}, 1},
        {"The Mekong River flows through how many countries?",
         {"3", "4", "5", "6"}, 3},
        {"Which river forms part of the border between USA and Mexico?",
         {"Colorado", "Rio Grande", "Mississippi", "Missouri"}, 1},
        {"What is the longest river in Europe?",
         {"Danube", "Rhine", "Volga", "Seine"}, 2},

        // ── Mountains & Geology ──────────────────────────────────────────
        {"Which mountain range runs along South America?",
         {"Rockies", "Himalayas", "Alps", "Andes"}, 3},
        {"Mount Fuji is in which country?",
         {"China", "South Korea", "Japan", "Taiwan"}, 2},
        {"What is the tallest mountain in Africa?",
         {"Mount Kenya", "Mount Kilimanjaro", "Mount Elgon", "Mount Stanley"}, 1},
        {"The Alps are mainly in which two countries?",
         {"France & Italy", "Switzerland & Austria", "Germany & France", "Italy & Slovenia"}, 1},
        {"What is the tallest mountain in North America?",
         {"Mount Whitney", "Mount Logan", "Denali", "Mount Rainier"}, 2},
        {"In which country is Mount Elbrus?",
         {"Georgia", "Turkey", "Russia", "Kazakhstan"}, 2},
        {"The Pyrenees separate which two countries?",
         {"France & Italy", "Spain & Portugal", "France & Spain", "Spain & Morocco"}, 2},
        {"What is the tallest mountain in Europe?",
         {"Mont Blanc", "Mount Elbrus", "Matterhorn", "Mount Olympus"}, 1},
        {"What type of rock is marble?",
         {"Igneous", "Sedimentary", "Metamorphic", "Volcanic"}, 2},
        {"Which country has the most active volcanoes?",
         {"Japan", "Indonesia", "Iceland", "Philippines"}, 1},
        {"Mount Vesuvius destroyed which ancient city?",
         {"Rome", "Athens", "Pompeii", "Carthage"}, 2},
        {"The Himalayas are in which continent?",
         {"Europe", "Africa", "Asia", "South America"}, 2},

        // ── Islands & Archipelagos ───────────────────────────────────────
        {"Which is the largest island in the Mediterranean?",
         {"Corsica", "Crete", "Sicily", "Sardinia"}, 2},
        {"Madagascar is off the coast of which continent?",
         {"Asia", "South America", "Africa", "Australia"}, 2},
        {"The Galapagos Islands belong to which country?",
         {"Peru", "Chile", "Ecuador", "Colombia"}, 2},
        {"Hawaii is in which ocean?",
         {"Atlantic", "Indian", "Arctic", "Pacific"}, 3},
        {"Which island country is the largest in the Caribbean?",
         {"Jamaica", "Cuba", "Haiti", "Puerto Rico"}, 1},
        {"Bali is an island in which country?",
         {"Thailand", "Philippines", "Malaysia", "Indonesia"}, 3},
        {"The Canary Islands belong to which country?",
         {"Portugal", "Morocco", "Spain", "France"}, 2},
        {"Which country consists of 7,641 islands?",
         {"Indonesia", "Japan", "Philippines", "Greece"}, 2},
        {"Borneo is shared by how many countries?",
         {"2", "3", "4", "1"}, 1},
        {"Which archipelago is known as the Spice Islands?",
         {"Maldives", "Comoros", "Maluku Islands", "Seychelles"}, 2},

        // ── Climate & Nature ─────────────────────────────────────────────
        {"Which country has the most rainforest?",
         {"Indonesia", "Congo", "Brazil", "Peru"}, 2},
        {"What is the hottest continent on average?",
         {"Asia", "Africa", "South America", "Australia"}, 1},
        {"The Northern Lights are best seen where?",
         {"Equator", "Tropics", "Southern Hemisphere", "Arctic regions"}, 3},
        {"What is the driest continent?",
         {"Africa", "Asia", "Antarctica", "Australia"}, 2},
        {"Which biome covers the most land area on Earth?",
         {"Desert", "Tropical Rainforest", "Taiga (Boreal Forest)", "Grassland"}, 2},
        {"In which country can you find the Serengeti?",
         {"Kenya", "Tanzania", "South Africa", "Botswana"}, 1},
        {"The Great Smoky Mountains are in which country?",
         {"Canada", "Mexico", "USA", "Colombia"}, 2},
        {"Which country has the most biodiversity?",
         {"China", "Brazil", "Indonesia", "Australia"}, 1},
        {"Where is the Gobi Desert?",
         {"Saudi Arabia", "Mongolia/China", "Pakistan", "Iran"}, 1},
        {"What is the largest coral reef system?",
         {"Belize Barrier Reef", "Great Barrier Reef", "Red Sea Reef", "Maldives Reef"}, 1},

        // ── Population & Demographics ────────────────────────────────────
        {"Which country is the most densely populated?",
         {"India", "Bangladesh", "Monaco", "Singapore"}, 2},
        {"Which continent has the fewest people?",
         {"South America", "Australia", "Antarctica", "Europe"}, 2},
        {"What is the most populated city in Africa?",
         {"Cairo", "Lagos", "Kinshasa", "Johannesburg"}, 1},
        {"Which European country has the largest population?",
         {"Germany", "France", "UK", "Italy"}, 0},
        {"What is the least populated country in the world?",
         {"Vatican City", "Nauru", "Tuvalu", "San Marino"}, 0},
        {"Which is the most visited city in the world?",
         {"Paris", "Bangkok", "London", "Dubai"}, 1},
        {"Which country has the highest life expectancy?",
         {"Japan", "Switzerland", "Monaco", "Singapore"}, 0},
        {"What is the most populous Muslim-majority country?",
         {"Saudi Arabia", "Pakistan", "Indonesia", "Iran"}, 2},
        {"Which South American country has the most people?",
         {"Argentina", "Colombia", "Brazil", "Peru"}, 2},

        // ── Borders & Neighbors ──────────────────────────────────────────
        {"Which country borders only Spain?",
         {"Portugal", "Andorra", "Gibraltar", "Morocco"}, 0},
        {"How many countries does Germany border?",
         {"5", "7", "9", "11"}, 2},
        {"Which two countries share the border at Niagara Falls?",
         {"USA & Mexico", "USA & Canada", "Canada & France", "USA & UK"}, 1},
        {"Which country is completely surrounded by South Africa?",
         {"Swaziland", "Lesotho", "Botswana", "Mozambique"}, 1},
        {"Which European country borders the most other countries?",
         {"France", "Germany", "Russia", "Austria"}, 1},
        {"Which two countries are doubly landlocked?",
         {"Mongolia & Nepal", "Bolivia & Paraguay", "Liechtenstein & Uzbekistan", "Chad & Mali"}, 2},
        {"Which African country borders the most others?",
         {"Nigeria", "DRC", "Sudan", "Tanzania"}, 1},
        {"The Khyber Pass connects which two countries?",
         {"India & China", "Iran & Iraq", "Afghanistan & Pakistan", "Turkey & Syria"}, 2},

        // ── Food & Agriculture ───────────────────────────────────────────
        {"Which country is the largest producer of rice?",
         {"India", "Thailand", "China", "Vietnam"}, 2},
        {"Sushi originated in which country?",
         {"China", "Japan", "Korea", "Thailand"}, 1},
        {"Which country produces the most olive oil?",
         {"Italy", "Greece", "Spain", "Turkey"}, 2},
        {"Maple syrup is mainly produced in which country?",
         {"USA", "Canada", "Finland", "Norway"}, 1},
        {"Which country consumes the most tea per capita?",
         {"China", "India", "Turkey", "UK"}, 2},
        {"Parmesan cheese originates from which country?",
         {"France", "Switzerland", "Spain", "Italy"}, 3},
        {"Which country is the largest producer of cocoa?",
         {"Brazil", "Ivory Coast", "Ghana", "Indonesia"}, 1},
        {"Tequila comes from which country?",
         {"Brazil", "Spain", "Cuba", "Mexico"}, 3},
        {"Which country is famous for paella?",
         {"Italy", "Portugal", "Spain", "France"}, 2},
        {"Kimchi is a traditional dish from which country?",
         {"Japan", "China", "Vietnam", "South Korea"}, 3},

        // ── Landmarks & Wonders ──────────────────────────────────────────
        {"The Colosseum is in which city?",
         {"Athens", "Rome", "Istanbul", "Cairo"}, 1},
        {"Where is the Eiffel Tower?",
         {"London", "Berlin", "Paris", "Brussels"}, 2},
        {"Christ the Redeemer is in which city?",
         {"Buenos Aires", "Lima", "Sao Paulo", "Rio de Janeiro"}, 3},
        {"The Forbidden City is in which country?",
         {"Japan", "China", "Vietnam", "South Korea"}, 1},
        {"Petra, the Rose City, is in which country?",
         {"Egypt", "Israel", "Jordan", "Syria"}, 2},
        {"Where is the Sagrada Familia?",
         {"Madrid", "Lisbon", "Barcelona", "Rome"}, 2},
        {"The Statue of Liberty was a gift from which country?",
         {"UK", "Spain", "France", "Netherlands"}, 2},
        {"Angkor Wat is in which country?",
         {"Thailand", "Vietnam", "Cambodia", "Laos"}, 2},
        {"Where is the Blue Mosque?",
         {"Cairo", "Istanbul", "Tehran", "Marrakech"}, 1},
        {"The Acropolis is in which city?",
         {"Rome", "Athens", "Sparta", "Istanbul"}, 1},
        {"Where is the Burj Khalifa?",
         {"Riyadh", "Doha", "Dubai", "Abu Dhabi"}, 2},
        {"Stonehenge is in which country?",
         {"Ireland", "Scotland", "England", "Wales"}, 2},
        {"The Kremlin is in which city?",
         {"St. Petersburg", "Kiev", "Moscow", "Minsk"}, 2},
        {"Where is Table Mountain?",
         {"Kenya", "Tanzania", "South Africa", "Zimbabwe"}, 2},
        {"The Parthenon was built by the ancient?",
         {"Romans", "Greeks", "Egyptians", "Persians"}, 1},

        // ── Transport & Infrastructure ───────────────────────────────────
        {"Which country has the longest railway network?",
         {"China", "Russia", "USA", "India"}, 2},
        {"The Trans-Siberian Railway crosses which country?",
         {"China", "Mongolia", "Russia", "Kazakhstan"}, 2},
        {"The Channel Tunnel connects which two countries?",
         {"UK & France", "UK & Ireland", "France & Spain", "UK & Belgium"}, 0},
        {"Which city has the oldest metro system?",
         {"New York", "Paris", "London", "Moscow"}, 2},
        {"The Suez Canal is in which country?",
         {"Saudi Arabia", "Israel", "Egypt", "Turkey"}, 2},

        // ── History & Geography Crossover ────────────────────────────────
        {"Constantinople is now called?",
         {"Athens", "Ankara", "Istanbul", "Sofia"}, 2},
        {"Which empire built Machu Picchu?",
         {"Aztec", "Maya", "Inca", "Olmec"}, 2},
        {"The Silk Road connected China to where?",
         {"Japan", "India", "Europe", "Africa"}, 2},
        {"Which country was formerly known as Persia?",
         {"Iraq", "Iran", "Turkey", "Afghanistan"}, 1},
        {"The Berlin Wall divided which city?",
         {"Munich", "Berlin", "Hamburg", "Vienna"}, 1},
        {"Which country was formerly called Siam?",
         {"Vietnam", "Myanmar", "Thailand", "Cambodia"}, 2},
        {"Rhodesia is now known as?",
         {"Zambia", "Zimbabwe", "Botswana", "Mozambique"}, 1},
        {"Which city was the capital of the Byzantine Empire?",
         {"Rome", "Athens", "Constantinople", "Alexandria"}, 2},
        {"Ceylon is the old name for which country?",
         {"Nepal", "Myanmar", "Maldives", "Sri Lanka"}, 3},
        {"Abyssinia is the old name for?",
         {"Somalia", "Ethiopia", "Sudan", "Eritrea"}, 1},

        // ── Unique Geography ─────────────────────────────────────────────
        {"Which country has territory on every continent?",
         {"UK", "France", "USA", "Russia"}, 1},
        {"What is the flattest country in the world?",
         {"Netherlands", "Denmark", "Maldives", "Bangladesh"}, 2},
        {"Which country is the narrowest in the world?",
         {"Chile", "Norway", "Gambia", "Panama"}, 2},
        {"What country has the most time zones?",
         {"Russia", "USA", "China", "France"}, 3},
        {"Which country straddles two continents?",
         {"Egypt", "Russia", "Turkey", "All of these"}, 3},
        {"What is the largest landlocked country?",
         {"Mongolia", "Kazakhstan", "Bolivia", "Chad"}, 1},
        {"How many countries are in Africa?",
         {"44", "48", "54", "60"}, 2},
        {"How many countries are in Europe?",
         {"34", "44", "50", "28"}, 1},
        {"Which country has the most neighbors?",
         {"Germany", "China", "Brazil", "Russia"}, 1},
        {"What is the southernmost capital city?",
         {"Buenos Aires", "Wellington", "Canberra", "Santiago"}, 1},
        {"The equator passes through how many countries?",
         {"7", "11", "13", "15"}, 2},
        {"Which is the only country whose name begins with Q?",
         {"Quatar", "Quebec", "Qatar", "Quito"}, 2},
        {"What is the most common official language?",
         {"Spanish", "English", "French", "Arabic"}, 1},
        {"Which country has the longest name?",
         {"United Kingdom", "Bosnia and Herzegovina", "St Vincent and the Grenadines", "United Kingdom of Great Britain and Northern Ireland"}, 3},
        {"How many landlocked countries are in South America?",
         {"1", "2", "3", "4"}, 1},

        // ── Sports & Geography ───────────────────────────────────────────
        {"The FIFA World Cup 2022 was held in?",
         {"Russia", "Qatar", "USA", "Brazil"}, 1},
        {"Where were the first modern Olympics held?",
         {"Rome", "Paris", "Athens", "London"}, 2},
        {"Cricket is the national sport of which country?",
         {"India", "England", "Australia", "None - it's not official"}, 3},
        {"The Tour de France ends in which city?",
         {"Marseille", "Lyon", "Paris", "Nice"}, 2},
        {"Which country has won the most FIFA World Cups?",
         {"Germany", "Argentina", "Italy", "Brazil"}, 3},
        {"The Marathon race is named after a battle in?",
         {"Italy", "Turkey", "Greece", "Egypt"}, 2},

        // ── Economy & Trade ──────────────────────────────────────────────
        {"Which country exports the most oil?",
         {"USA", "Russia", "Saudi Arabia", "Canada"}, 2},
        {"Silicon Valley is in which US state?",
         {"Texas", "New York", "Washington", "California"}, 3},
        {"Which African country has the largest economy?",
         {"South Africa", "Nigeria", "Egypt", "Kenya"}, 1},
        {"Which country is the largest exporter of goods?",
         {"USA", "Germany", "Japan", "China"}, 3},
        {"The Euro is used in how many countries?",
         {"15", "20", "25", "27"}, 1},
        {"Which country has the highest GDP per capita?",
         {"USA", "Luxembourg", "Switzerland", "Norway"}, 1},

        // ── Animals & Geography ──────────────────────────────────────────
        {"Kangaroos are native to which country?",
         {"South Africa", "New Zealand", "Australia", "Indonesia"}, 2},
        {"The giant panda is native to which country?",
         {"Japan", "Thailand", "China", "Vietnam"}, 2},
        {"Lemurs are only found in the wild in?",
         {"Africa mainland", "Madagascar", "Indonesia", "India"}, 1},
        {"Where do penguins NOT live in the wild?",
         {"South America", "Africa", "Arctic", "Antarctica"}, 2},
        {"The Komodo dragon comes from which country?",
         {"Thailand", "Philippines", "Indonesia", "Malaysia"}, 2},
        {"Which country has the most tigers in the wild?",
         {"China", "Russia", "Indonesia", "India"}, 3},
        {"The bald eagle is the national bird of?",
         {"Canada", "Mexico", "USA", "Russia"}, 2},
        {"Kiwi birds are from which country?",
         {"Australia", "Fiji", "New Zealand", "Papua New Guinea"}, 2},

        // ── Maps & Directions ────────────────────────────────────────────
        {"Which hemisphere has more land mass?",
         {"Northern", "Southern", "Eastern", "Western"}, 0},
        {"The Prime Meridian passes through which city?",
         {"Paris", "London", "Berlin", "New York"}, 1},
        {"The International Date Line is near which meridian?",
         {"0 degrees", "90 degrees", "180 degrees", "45 degrees"}, 2},
        {"How many continents touch the equator?",
         {"2", "3", "4", "5"}, 1},
        {"The Tropic of Cancer is in which hemisphere?",
         {"Southern", "Northern", "Both", "Neither"}, 1},
        {"Which ocean is between Africa and Australia?",
         {"Pacific", "Atlantic", "Indian", "Southern"}, 2},
    };
    return catalog;
}

/// Return a shuffled sequence of question indices for variety.
inline std::vector<int> shuffledQuizIndices(std::mt19937& rng) {
    auto& catalog = getQuizCatalog();
    std::vector<int> idx(catalog.size());
    for (size_t i = 0; i < idx.size(); ++i) idx[i] = static_cast<int>(i);
    std::shuffle(idx.begin(), idx.end(), rng);
    return idx;
}

} // namespace is::games::country_elimination
